# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a08ccb9db86317b4dbbb86ac46cc7573b43ead066216c8ab2f0cf9b4a9db1a09a3e00bde06ae38a6cf4e66219a9a3d7ce6f851ba6f1cd07694d5b1bf82475c9

test:
  secret_key_base: 53fe54c7094d74d9a1e0c62dca17dbe2525d154f80d0fe7c6f9a842c0f26a302e4a5443e04535796204d6c7e3ca8964ff27e3aaef58a529b7e59e0131368adc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
